sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # you need to google how to install the google cloud sdk
  # the other side of the pipe installs it on travis
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # install and update kubectl to run imperative commands
  - gcloud components update kubectl
  # service-account.json has our credentials
  - gcloud auth activate-service-account --key-file service-account.json